name: PHP Selenium Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache php dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install php dependencies
        run: composer install --prefer-dist

  test:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: php:7.4-apache
      ports: 
        - 80:80
      options: --network-alias=testserver

    env:
      TEST_BASE_URL: http://testserver
      SELENIUM_HOST: http://selenium:4444/wd/hub

    services:
      selenium:
        image: selenium/standalone-chrome
        # options: --health-cmd "curl http://selenium:4444" --health-interval=5s
        ports:
          - 4444:4444
      
    steps:

    - name: Wait for the Apache server to be ready
      run: |
        for i in {1..10}; do
          curl -s $TEST_BASE_URL && break || sleep 3
        done

    - name: Check if site is accessible
      run: |
        curl -f $TEST_BASE_URL || echo "Site not accessible"

    - name: Wait for the Selenium server to be up
      run: |
        for i in {1..10}; do
          curl -s $SELENIUM_HOST && break || sleep 3
        done

    - name: Run Selenium tests
      run: php tests/SeleniumTest.php
