name: PHP Selenium Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install

      - name: Start PHP server
        run: php -S 127.0.0.1:8000 -t . &  # Start PHP server in the background

      - name: Wait for the server to be up
        run: sleep 5  # Wait for the server to start up

      - name: Run Selenium tests
        run: php tests/SeleniumTest.php

