name: PHP Selenium Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache php dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install php dependencies
        run: composer install --prefer-dist

  test:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: php:7.4-apache
      ports: 
        - 80:80
      options: --network-alias=testserver 
    env:
      TEST_BASE_URL: http://testserver
      SELENIUM_HOST: http://selenium:4444/wd/hub

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --network-alias=selenium
        ports:
          - 4444:4444
      
    steps:

#      - name: Restart apache server
#        run: service apache2 restart

      - name: Check if site is accessible
        run: |
          curl $TEST_BASE_URL

      - name: List open ports (for debugging)
        run: netstat -tuln;ls -ltra .;docker ps

      - name: Check if port 8000 is open
        run: |
          sudo netstat -tuln | grep 8000 || echo "Port 8000 is not open"

      - name: Wait for the server to be up
        run: sleep 5  # Wait for the server to start up

      - name: Run Selenium tests
        run: php tests/SeleniumTest.php
