name: PHP Selenium Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: php:7.4-apache
      ports: 
        - 80:80
      options: --network-alias=testserver 

  env:
    TEST_BASE_URL: http://testserver
    SELENIUM_HOST: http://selenium:4444/wd/hub

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --network-alias=selenium
        ports:
          - 4444:4444
      
    steps:
      - name: Download built files
        uses: actions/download-artifact@v2
        with:
          name: www-build

      - name: Extract artifacts
        run: |
          tar -xzf www-build.tar.gz
          ls -l

      - name: Copy files to web root
        run: |
          cp -R ./www/* /var/www/html

      - name: Restart apache server
        run: service apache2 restart

      - name: Check if site is accessible
        run: |
          curl $TEST_BASE_URL

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: List open ports (for debugging)
        run: netstat -tuln;ls -ltra .;docker ps

      - name: Check if port 8000 is open
        run: |
          sudo netstat -tuln | grep 8000 || echo "Port 8000 is not open"

      - name: Wait for the server to be up
        run: sleep 5  # Wait for the server to start up

      - name: Run Selenium tests
        run: php tests/SeleniumTest.php
