name: PHP Selenium Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        container_name: selenium
        ports:
          - 4444:4444
      
      php:
        image: php:8.0-apache
        container_name: php
        ports:
          - 8000:8000
        volumes:
          - ./:/var/www/html/

    steps:
#      - name: Start Selenium container
#        run: |
#          docker run --name selenium-standalone -d \
#          --network host \
#          -p 4444:4444 selenium/standalone-chrome:latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install

#      - name: Start PHP server
#        run: php -S 0.0.0.0:8000 -t . &  # Bind PHP server to 0.0.0.0 for external access

      - name: List open ports (for debugging)
        run: netstat -tuln;ls -ltra .;docker ps

      - name: Check if port 8000 is open
        run: |
          sudo netstat -tuln | grep 8000 || echo "Port 8000 is not open"

      - name: Run a curl test from the Selenium container
        run: docker exec selenium curl http://localhost:8000/index.php || echo "Connection failed"

      - name: Wait for the server to be up
        run: sleep 15  # Wait for the server to start up

      - name: Run Selenium tests
        run: php tests/SeleniumTest.php
